# Generated by Django 6.0.4 on 2026-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imo', models.CharField(max_length=50)),
                ('flag', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('vessel_type', models.CharField(max_length=100)),
            ],
        ),
    ]
